#!/usr/bin/env bash
[ "$2" ] || { echo >&2 "usage: ./$0 YYYY DD"; exit 1; }
YYYY=$1
DD=$2
[ -f "$YYYY/input/$DD.txt" ] && { echo >&2 "looks like this was already downloaded"; exit 1; }

mkdir -p "$YYYY/input"
cat >$YYYY/day-$DD.py <<EOF
from os.path import dirname
with open(dirname(__file__) + "/input/$DD.txt") as f:
    input = f.read()
EOF

# I logged in through the browser and get asession id, and saved it as `session=abcd....` in ~/secrets/advent
d=$(sed s/^0// <<< "$DD")
curl -sS --cookie $(<~/secrets/advent) https://adventofcode.com/$YYYY/day/$d/input >$YYYY/input/$DD.txt && chmod a-w $YYYY/input/$DD.txt
