#!/usr/bin/env bash
# a kitchen sink for aoc puzzles


function goto_year {
  [ "$1" ] || set -- $(ls -d 20??|tail -n1)
  cd "$1"
}

function get_file {
  [ "$1" ] || set -- ".."
  ls *.py | grep "day-$1\.py"| tail -n1
}


case "$1%$2" in
        %) goto_year;      f=$(get_file)      ;;
      ??%) goto_year;      f=$(get_file "$1") ;;
    20??%) goto_year "$1"; f=$(get_file)      ;;
  20??%??) goto_year "$1"; f=$(get_file "$2") ;;
        *)
           echo >&2 "uh oh...got [$1 $2]"
           exit 1
        ;;
esac


echo "$f"
poetry run python "$f"


# got a bunch of ideas here, and I'm not sure which are good.
# I'll copy some above this line and try them out!
exit








now_y=$(date +%Y)
now_m=$(date +%m)
now_d=$(date +%d)

case "$1" in
  [0-9[0-9][0-9][0-9])
    echo "year";;
  [0-9][0-9])
    echo "day";;
  *)
    echo "other";;
esac

exit


day=$(date +%d)
txt="input-$day.txt"
src="day-$day.py"

[ -e "$txt" -o -e "$src" ] && {
  echo "already got files for today!"
  exit
}

touch "$txt" "$src"

cat - >"$src" <<EOF
def input():
    with open("$txt") as lines:
        for line in lines:
            yield line.strip()
EOF



[ "$1" ] || set -- $(ls day*.py|tail -n1)
[ "$1" = "all" ] && set -- $(ls day*.py)

set -e
for day in "$@"; do
  echo "$day"
  poetry run python "$day"
done
